-- Binding Variables
BINDING_HEADER_TARGETCLASSBUTTON = "Target Class Button"
BINDING_NAME_INSPECT = INSPECT
BINDING_NAME_TRADE = TRADE
BINDING_NAME_WHISPER = WHISPER
BINDING_NAME_FOLLOW = FOLLOW
--BINDING_NAME_COMPARE_ACHIEVEMENTS = COMPARE_ACHIEVEMENTS
BINDING_NAME_Invite = Invite
